name: mec_brain
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - nibabel
  - numpy
  - pandas
  - tensorboard
  - pyvista
  - matplotlib
  - tqdm
  - python-graphviz
  - scipy
  - scikit-learn
  - seaborn
  - jupyter
  - scikit-image
  - umap-learn
  - pingouin
  - pip:
    - torch
    - torchvision
    - "ray[tune]"
    - torchio
    - openpyxl
    - torcheval
